// GENERATED by tool/generate-practice-catalog.mjs. Edit the versioned source catalog.
// Source SHA-256: 1de12d831bf1611078968028c55cb03c66415758f0ad1a59acf5423499a1f88d
export const practiceCatalogSchemaVersion = 2 as const;
export const practiceCatalogContentVersion = "2026-09-15.1" as const;
export const practiceCatalogPayloadVersion = 6 as const;
export const practiceCatalogFloors = Object.freeze({
  1: "Read the evidence",
  2: "Understand the numbers",
  3: "Work with the team",
  4: "Make the plan",
} as const);
export const practiceCatalogActivityIds = Object.freeze([
  "check-the-date",
  "sales-and-profit",
  "check-the-sample",
  "prepare-the-update",
  "compare-company-value",
  "count-the-fees",
  "check-concentration",
  "prepare-the-comparison",
  "review-team-update",
  "read-returned-costs",
  "finish-team-update",
  "set-a-loss-limit",
  "plan-not-a-promise",
  "write-the-plan",
] as const);
export type PracticeCatalogActivityId = typeof practiceCatalogActivityIds[number];
export const practiceCatalogById = Object.freeze({
  "check-the-date": Object.freeze({
    id: "check-the-date",
    floor: 1,
    title: "Check the date",
    correctChoiceId: "add-year",
    choiceIds: Object.freeze([
      "add-year",
      "keep-headline",
    ] as const),
    acceptedChoiceIds: Object.freeze([
      "add-year",
    ] as const),
    introducedIn: 1,
    prerequisiteId: null,
  } as const),
  "sales-and-profit": Object.freeze({
    id: "sales-and-profit",
    floor: 1,
    title: "Sales and profit",
    correctChoiceId: "check-costs",
    choiceIds: Object.freeze([
      "check-costs",
      "sales-mean-profit",
    ] as const),
    acceptedChoiceIds: Object.freeze([
      "check-costs",
    ] as const),
    introducedIn: 1,
    prerequisiteId: "check-the-date",
  } as const),
  "check-the-sample": Object.freeze({
    id: "check-the-sample",
    floor: 1,
    title: "Check the sample",
    correctChoiceId: "eight-of-ten-testers",
    choiceIds: Object.freeze([
      "eight-of-ten-testers",
      "all-testers",
      "eight-of-ten-customers",
      "all-customers",
    ] as const),
    acceptedChoiceIds: Object.freeze([
      "eight-of-ten-testers",
    ] as const),
    introducedIn: 2,
    prerequisiteId: "sales-and-profit",
  } as const),
  "prepare-the-update": Object.freeze({
    id: "prepare-the-update",
    floor: 1,
    title: "Prepare the update",
    correctChoiceId: "dated-growth+lower-profit+trial-result",
    choiceIds: Object.freeze([
      "dated-growth+lower-profit+trial-result",
      "dated-growth+lower-profit+current-growth",
      "dated-growth+lower-profit+all-customers",
      "dated-growth+trial-result+current-growth",
      "dated-growth+trial-result+all-customers",
      "dated-growth+current-growth+all-customers",
      "lower-profit+trial-result+current-growth",
      "lower-profit+trial-result+all-customers",
      "lower-profit+current-growth+all-customers",
      "trial-result+current-growth+all-customers",
    ] as const),
    acceptedChoiceIds: Object.freeze([
      "dated-growth+lower-profit+trial-result",
    ] as const),
    introducedIn: 3,
    prerequisiteId: "check-the-sample",
  } as const),
  "compare-company-value": Object.freeze({
    id: "compare-company-value",
    floor: 2,
    title: "Compare company value",
    correctChoiceId: "compare-total-value",
    choiceIds: Object.freeze([
      "compare-total-value",
      "lower-price-means-smaller",
    ] as const),
    acceptedChoiceIds: Object.freeze([
      "compare-total-value",
    ] as const),
    introducedIn: 4,
    prerequisiteId: "prepare-the-update",
  } as const),
  "count-the-fees": Object.freeze({
    id: "count-the-fees",
    floor: 2,
    title: "Count the fees",
    correctChoiceId: "nine-dollars-invested",
    choiceIds: Object.freeze([
      "nine-dollars-invested",
      "ten-dollars-invested",
    ] as const),
    acceptedChoiceIds: Object.freeze([
      "nine-dollars-invested",
    ] as const),
    introducedIn: 4,
    prerequisiteId: "compare-company-value",
  } as const),
  "check-concentration": Object.freeze({
    id: "check-concentration",
    floor: 2,
    title: "Check concentration",
    correctChoiceId: "eighty-percent-aster",
    choiceIds: Object.freeze([
      "eighty-percent-aster",
      "three-equal-companies",
    ] as const),
    acceptedChoiceIds: Object.freeze([
      "eighty-percent-aster",
    ] as const),
    introducedIn: 4,
    prerequisiteId: "count-the-fees",
  } as const),
  "prepare-the-comparison": Object.freeze({
    id: "prepare-the-comparison",
    floor: 2,
    title: "Prepare the comparison",
    correctChoiceId: "include-value-fees-and-risk",
    choiceIds: Object.freeze([
      "include-value-fees-and-risk",
      "choose-cheapest-share",
      "ignore-the-fee",
    ] as const),
    acceptedChoiceIds: Object.freeze([
      "include-value-fees-and-risk",
    ] as const),
    introducedIn: 4,
    prerequisiteId: "check-concentration",
  } as const),
  "review-team-update": Object.freeze({
    id: "review-team-update",
    floor: 3,
    title: "Review the team’s update",
    correctChoiceId: "share-qualified-sales",
    choiceIds: Object.freeze([
      "share-qualified-sales",
      "request-missing-costs",
    ] as const),
    acceptedChoiceIds: Object.freeze([
      "share-qualified-sales",
      "request-missing-costs",
    ] as const),
    introducedIn: 5,
    prerequisiteId: "prepare-the-comparison",
  } as const),
  "read-returned-costs": Object.freeze({
    id: "read-returned-costs",
    floor: 3,
    title: "Read the returned costs",
    correctChoiceId: "compare-sales-and-costs",
    choiceIds: Object.freeze([
      "compare-sales-and-costs",
      "repeat-sales-only",
    ] as const),
    acceptedChoiceIds: Object.freeze([
      "compare-sales-and-costs",
    ] as const),
    introducedIn: 5,
    prerequisiteId: "review-team-update",
  } as const),
  "finish-team-update": Object.freeze({
    id: "finish-team-update",
    floor: 3,
    title: "Finish the team’s update",
    correctChoiceId: "apply-returned-figures",
    choiceIds: Object.freeze([
      "apply-returned-figures",
      "leave-earlier-action",
    ] as const),
    acceptedChoiceIds: Object.freeze([
      "apply-returned-figures",
    ] as const),
    introducedIn: 5,
    prerequisiteId: "read-returned-costs",
  } as const),
  "set-a-loss-limit": Object.freeze({
    id: "set-a-loss-limit",
    floor: 4,
    title: "Set a loss limit",
    correctChoiceId: "commit-spare-only",
    choiceIds: Object.freeze([
      "commit-spare-only",
      "commit-everything",
    ] as const),
    acceptedChoiceIds: Object.freeze([
      "commit-spare-only",
    ] as const),
    introducedIn: 6,
    prerequisiteId: "finish-team-update",
  } as const),
  "plan-not-a-promise": Object.freeze({
    id: "plan-not-a-promise",
    floor: 4,
    title: "A plan is not a promise",
    correctChoiceId: "state-actions-and-limits",
    choiceIds: Object.freeze([
      "state-actions-and-limits",
      "promise-a-return",
    ] as const),
    acceptedChoiceIds: Object.freeze([
      "state-actions-and-limits",
    ] as const),
    introducedIn: 6,
    prerequisiteId: "set-a-loss-limit",
  } as const),
  "write-the-plan": Object.freeze({
    id: "write-the-plan",
    floor: 4,
    title: "Write the plan",
    correctChoiceId: "keep-limit-and-no-promise",
    choiceIds: Object.freeze([
      "keep-limit-and-no-promise",
      "drop-the-limit",
      "promise-the-gain",
    ] as const),
    acceptedChoiceIds: Object.freeze([
      "keep-limit-and-no-promise",
    ] as const),
    introducedIn: 6,
    prerequisiteId: "plan-not-a-promise",
  } as const),
} as const);
export type PracticeCatalogEntry = typeof practiceCatalogById[PracticeCatalogActivityId];
