// GENERATED by tool/generate-practice-catalog.mjs. Edit the versioned source catalog.
// Source SHA-256: 1de12d831bf1611078968028c55cb03c66415758f0ad1a59acf5423499a1f88d

const practiceCatalogSchemaVersion = 2;
const practiceCatalogContentVersion = '2026-09-15.1';
const practiceCatalogPayloadVersion = 6;

class PracticeCatalogEntry {
  const PracticeCatalogEntry({
    required this.id,
    required this.floor,
    required this.title,
    required this.correctChoiceId,
    required this.choiceIds,
    required this.acceptedChoiceIds,
    required this.introducedIn,
    required this.prerequisiteId,
  });

  final String id;
  final int floor;
  final String title;
  final String correctChoiceId;
  final List<String> choiceIds;
  final List<String> acceptedChoiceIds;
  final int introducedIn;
  final String? prerequisiteId;
}

const practiceCatalogFloors = <int, String>{
  1: 'Read the evidence',
  2: 'Understand the numbers',
  3: 'Work with the team',
  4: 'Make the plan',
};

const practiceCatalogActivityIds = <String>[
  'check-the-date',
  'sales-and-profit',
  'check-the-sample',
  'prepare-the-update',
  'compare-company-value',
  'count-the-fees',
  'check-concentration',
  'prepare-the-comparison',
  'review-team-update',
  'read-returned-costs',
  'finish-team-update',
  'set-a-loss-limit',
  'plan-not-a-promise',
  'write-the-plan',
];

const practiceCatalogById = <String, PracticeCatalogEntry>{
  'check-the-date': PracticeCatalogEntry(
    id: 'check-the-date',
    floor: 1,
    title: 'Check the date',
    correctChoiceId: 'add-year',
    choiceIds: ['add-year', 'keep-headline'],
    acceptedChoiceIds: ['add-year'],
    introducedIn: 1,
    prerequisiteId: null,
  ),
  'sales-and-profit': PracticeCatalogEntry(
    id: 'sales-and-profit',
    floor: 1,
    title: 'Sales and profit',
    correctChoiceId: 'check-costs',
    choiceIds: ['check-costs', 'sales-mean-profit'],
    acceptedChoiceIds: ['check-costs'],
    introducedIn: 1,
    prerequisiteId: 'check-the-date',
  ),
  'check-the-sample': PracticeCatalogEntry(
    id: 'check-the-sample',
    floor: 1,
    title: 'Check the sample',
    correctChoiceId: 'eight-of-ten-testers',
    choiceIds: [
      'eight-of-ten-testers',
      'all-testers',
      'eight-of-ten-customers',
      'all-customers',
    ],
    acceptedChoiceIds: ['eight-of-ten-testers'],
    introducedIn: 2,
    prerequisiteId: 'sales-and-profit',
  ),
  'prepare-the-update': PracticeCatalogEntry(
    id: 'prepare-the-update',
    floor: 1,
    title: 'Prepare the update',
    correctChoiceId: 'dated-growth+lower-profit+trial-result',
    choiceIds: [
      'dated-growth+lower-profit+trial-result',
      'dated-growth+lower-profit+current-growth',
      'dated-growth+lower-profit+all-customers',
      'dated-growth+trial-result+current-growth',
      'dated-growth+trial-result+all-customers',
      'dated-growth+current-growth+all-customers',
      'lower-profit+trial-result+current-growth',
      'lower-profit+trial-result+all-customers',
      'lower-profit+current-growth+all-customers',
      'trial-result+current-growth+all-customers',
    ],
    acceptedChoiceIds: ['dated-growth+lower-profit+trial-result'],
    introducedIn: 3,
    prerequisiteId: 'check-the-sample',
  ),
  'compare-company-value': PracticeCatalogEntry(
    id: 'compare-company-value',
    floor: 2,
    title: 'Compare company value',
    correctChoiceId: 'compare-total-value',
    choiceIds: ['compare-total-value', 'lower-price-means-smaller'],
    acceptedChoiceIds: ['compare-total-value'],
    introducedIn: 4,
    prerequisiteId: 'prepare-the-update',
  ),
  'count-the-fees': PracticeCatalogEntry(
    id: 'count-the-fees',
    floor: 2,
    title: 'Count the fees',
    correctChoiceId: 'nine-dollars-invested',
    choiceIds: ['nine-dollars-invested', 'ten-dollars-invested'],
    acceptedChoiceIds: ['nine-dollars-invested'],
    introducedIn: 4,
    prerequisiteId: 'compare-company-value',
  ),
  'check-concentration': PracticeCatalogEntry(
    id: 'check-concentration',
    floor: 2,
    title: 'Check concentration',
    correctChoiceId: 'eighty-percent-aster',
    choiceIds: ['eighty-percent-aster', 'three-equal-companies'],
    acceptedChoiceIds: ['eighty-percent-aster'],
    introducedIn: 4,
    prerequisiteId: 'count-the-fees',
  ),
  'prepare-the-comparison': PracticeCatalogEntry(
    id: 'prepare-the-comparison',
    floor: 2,
    title: 'Prepare the comparison',
    correctChoiceId: 'include-value-fees-and-risk',
    choiceIds: [
      'include-value-fees-and-risk',
      'choose-cheapest-share',
      'ignore-the-fee',
    ],
    acceptedChoiceIds: ['include-value-fees-and-risk'],
    introducedIn: 4,
    prerequisiteId: 'check-concentration',
  ),
  'review-team-update': PracticeCatalogEntry(
    id: 'review-team-update',
    floor: 3,
    title: 'Review the team’s update',
    correctChoiceId: 'share-qualified-sales',
    choiceIds: ['share-qualified-sales', 'request-missing-costs'],
    acceptedChoiceIds: ['share-qualified-sales', 'request-missing-costs'],
    introducedIn: 5,
    prerequisiteId: 'prepare-the-comparison',
  ),
  'read-returned-costs': PracticeCatalogEntry(
    id: 'read-returned-costs',
    floor: 3,
    title: 'Read the returned costs',
    correctChoiceId: 'compare-sales-and-costs',
    choiceIds: ['compare-sales-and-costs', 'repeat-sales-only'],
    acceptedChoiceIds: ['compare-sales-and-costs'],
    introducedIn: 5,
    prerequisiteId: 'review-team-update',
  ),
  'finish-team-update': PracticeCatalogEntry(
    id: 'finish-team-update',
    floor: 3,
    title: 'Finish the team’s update',
    correctChoiceId: 'apply-returned-figures',
    choiceIds: ['apply-returned-figures', 'leave-earlier-action'],
    acceptedChoiceIds: ['apply-returned-figures'],
    introducedIn: 5,
    prerequisiteId: 'read-returned-costs',
  ),
  'set-a-loss-limit': PracticeCatalogEntry(
    id: 'set-a-loss-limit',
    floor: 4,
    title: 'Set a loss limit',
    correctChoiceId: 'commit-spare-only',
    choiceIds: ['commit-spare-only', 'commit-everything'],
    acceptedChoiceIds: ['commit-spare-only'],
    introducedIn: 6,
    prerequisiteId: 'finish-team-update',
  ),
  'plan-not-a-promise': PracticeCatalogEntry(
    id: 'plan-not-a-promise',
    floor: 4,
    title: 'A plan is not a promise',
    correctChoiceId: 'state-actions-and-limits',
    choiceIds: ['state-actions-and-limits', 'promise-a-return'],
    acceptedChoiceIds: ['state-actions-and-limits'],
    introducedIn: 6,
    prerequisiteId: 'set-a-loss-limit',
  ),
  'write-the-plan': PracticeCatalogEntry(
    id: 'write-the-plan',
    floor: 4,
    title: 'Write the plan',
    correctChoiceId: 'keep-limit-and-no-promise',
    choiceIds: [
      'keep-limit-and-no-promise',
      'drop-the-limit',
      'promise-the-gain',
    ],
    acceptedChoiceIds: ['keep-limit-and-no-promise'],
    introducedIn: 6,
    prerequisiteId: 'plan-not-a-promise',
  ),
};
