// Generated by tool/generate-desk-story-texts.mjs from content/. Do not edit.
// Text only: ids, choices and order come from the released desk stories in the database.
export type DeskStoryLanguage = 'en' | 'es' | 'pt' | 'fr';
export interface DeskStoryText {
  readonly title: string; readonly body: string;
  readonly choices: Readonly<Record<string, {readonly label: string; readonly outcome: string; readonly takeaway: string}>>;
}
export const DESK_STORY_CONTENT_VERSION = "desk-stories-v1";
export const DESK_STORY_TEXTS: Readonly<Record<DeskStoryLanguage, Readonly<Record<string, DeskStoryText>>>> = {
 "en": {
  "the-group-chat": {
   "title": "The group chat is loud.",
   "body": "Everyone is talking about Aster. “It’s going up,” says Wolf. The screenshot has no source. Your coffee isn’t even cold yet.",
   "choices": {
    "ask": {
     "label": "Ask for the source",
     "outcome": "Wolf sends the original post. It is three months old. You put the excitement on pause and open the company update.",
     "takeaway": "A screenshot is a starting point, not the whole story."
    },
    "wait": {
     "label": "Watch for a while",
     "outcome": "You leave Aster on your watchlist. Later, the chat gets quiet. You kept your options open without making a trade.",
     "takeaway": "Waiting is a decision too."
    },
    "follow": {
     "label": "Follow the crowd",
     "outcome": "In this story, you rush in. A second message contradicts the first. Now you have a position, but no reason you trust.",
     "takeaway": "Before following a crowd, write down what would change your mind."
    }
   }
  },
  "a-red-morning": {
   "title": "A red morning.",
   "body": "Aster is down 6% in this desk story. Sal drops a note beside your screen: “Price moved. What else changed?”",
   "choices": {
    "read": {
     "label": "Read the company update",
     "outcome": "Revenue is steady, but costs rose. You now have a fact to compare with your original plan.",
     "takeaway": "Price and business performance are different pieces of evidence."
    },
    "plan": {
     "label": "Open my original plan",
     "outcome": "Your note says you would review after the next results. You set the headline beside that plan before making a new call.",
     "takeaway": "A plan gives you something to revisit when emotions get loud."
    },
    "panic": {
     "label": "Sell because it is red",
     "outcome": "You react to the colour before reading the update. The story pauses there; selling may fit a plan, but red alone does not explain one.",
     "takeaway": "Ask what changed before choosing your response."
    }
   }
  },
  "one-big-position": {
   "title": "One very big position.",
   "body": "One company now makes up 70% of your fictional desk. Oracle turns the monitor towards you: “A good week made this desk very lopsided.”",
   "choices": {
    "inspect": {
     "label": "Look at the whole desk",
     "outcome": "You compare how much depends on this one company. A small move there could now dominate everything else.",
     "takeaway": "Look at position size as well as performance."
    },
    "trim": {
     "label": "Consider trimming it",
     "outcome": "You work through a smaller position on paper before acting. You are deciding how much uncertainty to carry.",
     "takeaway": "Reducing concentration is a risk decision, not a prediction."
    },
    "leave": {
     "label": "Leave it for now",
     "outcome": "You keep the position, and write down why you are comfortable with the concentration. You also choose when to review it.",
     "takeaway": "Keeping a position still deserves a deliberate reason."
    }
   }
  },
  "the-cheap-share": {
   "title": "“That share is cheaper.”",
   "body": "Shark points at two fictional companies: one share costs 5, the other 100. “Five is a bargain, right?”",
   "choices": {
    "compare": {
     "label": "Ask how many shares exist",
     "outcome": "The 5-priced company has far more shares. Share price alone did not tell you which whole business was cheaper.",
     "takeaway": "Price per share and the value of a company are different."
    },
    "business": {
     "label": "Look at the businesses",
     "outcome": "You put earnings, debt and expectations beside the price. There is more work to do before calling either a bargain.",
     "takeaway": "A low share price is not an investment case."
    },
    "cheap": {
     "label": "Pick the lower number",
     "outcome": "The low price catches your eye. Sal slides over the share counts; that single number was missing most of the comparison.",
     "takeaway": "The smallest number is not automatically the best value."
    }
   }
  },
  "the-friday-close": {
   "title": "Before you close the laptop.",
   "body": "It has been a noisy week. Sal leaves one empty note on your desk. You have time for one useful thing.",
   "choices": {
    "review": {
     "label": "Review one decision",
     "outcome": "You compare your reason with what happened. A good result can follow a weak process, and a careful decision can still lose.",
     "takeaway": "Review the reasoning as well as the result."
    },
    "write": {
     "label": "Write next week’s plan",
     "outcome": "You note one company to research and one question you still cannot answer. Monday now has a starting point.",
     "takeaway": "An unanswered question can be a useful next step."
    },
    "stop": {
     "label": "Take the evening off",
     "outcome": "You close the desk without forcing one more trade. The market will still be there when you return.",
     "takeaway": "You do not need a trade for every visit."
    }
   }
  },
  "know-what-you-hold": {
   "title": "Same company. Different token.",
   "body": "Two tokens follow the same company. Their names look familiar. Oracle puts their issuer pages side by side.",
   "choices": {
    "rights": {
     "label": "Read the issuer terms",
     "outcome": "The pages describe different rights and redemption routes. You check the token itself, not just the company name.",
     "takeaway": "A token linked to a share does not automatically give you every shareholder right."
    },
    "market": {
     "label": "Compare the markets",
     "outcome": "You notice different liquidity and prices. You add issuer terms to your checks before treating them as interchangeable.",
     "takeaway": "Company identity, token terms and trading conditions all matter."
    },
    "logo": {
     "label": "Trust the matching logo",
     "outcome": "The logos match, but the contracts and terms do not. You stop before assuming that the pictures prove equivalence.",
     "takeaway": "A familiar logo does not verify an asset."
    }
   }
  },
  "the-weekend-note": {
   "title": "A quieter desk.",
   "body": "No rush today. Sal asks you to pick one thing you want to understand better before the next busy day.",
   "choices": {
    "company": {
     "label": "How one company makes money",
     "outcome": "You make a short list: who pays, what they buy, and what it costs to deliver. You have a research plan for your next visit.",
     "takeaway": "Start with the business behind the symbol."
    },
    "risk": {
     "label": "What could go wrong",
     "outcome": "You name one assumption in your plan and what evidence would challenge it. Uncertainty is easier to discuss when it is specific.",
     "takeaway": "A risk is more useful when you can explain it."
    },
    "journal": {
     "label": "What I changed my mind about",
     "outcome": "You reread an old reason and add what you see differently now. Changing your mind can be part of a careful process.",
     "takeaway": "Keep a record of how your thinking changes."
    }
   }
  }
 },
 "es": {
  "the-group-chat": {
   "title": "El chat del grupo está agitado.",
   "body": "Todos hablan de Aster. “Va a subir”, dice Wolf. La captura de pantalla no tiene fuente. Tu café ni siquiera se ha enfriado.",
   "choices": {
    "ask": {
     "label": "Pedir la fuente",
     "outcome": "Wolf envía la publicación original. Tiene tres meses. Pones la emoción en pausa y abres la actualización de la empresa.",
     "takeaway": "Una captura de pantalla es un punto de partida, no toda la historia."
    },
    "wait": {
     "label": "Observar un rato",
     "outcome": "Dejas Aster en tu lista de seguimiento. Más tarde, el chat se calma. Mantuviste tus opciones abiertas sin hacer una operación.",
     "takeaway": "Esperar también es una decisión."
    },
    "follow": {
     "label": "Seguir a la multitud",
     "outcome": "En esta historia, entras con prisa. Un segundo mensaje contradice el primero. Ahora tienes una posición, pero ningún motivo en el que confíes.",
     "takeaway": "Antes de seguir a la multitud, anota qué te haría cambiar de opinión."
    }
   }
  },
  "a-red-morning": {
   "title": "Una mañana en rojo.",
   "body": "Aster baja un 6% en esta historia del escritorio. Sal deja una nota junto a tu pantalla: “El precio se movió. ¿Qué más cambió?”",
   "choices": {
    "read": {
     "label": "Leer la actualización de la empresa",
     "outcome": "Los ingresos se mantienen, pero los costos subieron. Ahora tienes un dato para comparar con tu plan original.",
     "takeaway": "El precio y el desempeño del negocio son evidencias distintas."
    },
    "plan": {
     "label": "Abrir mi plan original",
     "outcome": "Tu nota dice que revisarías después de los próximos resultados. Pones el titular junto a ese plan antes de tomar una nueva decisión.",
     "takeaway": "Un plan te da algo a qué volver cuando las emociones suben de tono."
    },
    "panic": {
     "label": "Vender porque está en rojo",
     "outcome": "Reaccionas al color antes de leer la actualización. La historia se detiene ahí: vender puede encajar en un plan, pero el rojo por sí solo no lo explica.",
     "takeaway": "Pregúntate qué cambió antes de elegir cómo responder."
    }
   }
  },
  "one-big-position": {
   "title": "Una posición muy grande.",
   "body": "Una sola empresa ya representa el 70% de tu escritorio ficticio. Oracle gira el monitor hacia ti: “Una buena semana dejó este escritorio muy desequilibrado”.",
   "choices": {
    "inspect": {
     "label": "Mirar todo el escritorio",
     "outcome": "Comparas cuánto depende de esta sola empresa. Un pequeño movimiento ahí podría pesar más que todo lo demás.",
     "takeaway": "Mira el tamaño de la posición, además del rendimiento."
    },
    "trim": {
     "label": "Pensar en reducirla",
     "outcome": "Calculas en papel una posición más pequeña antes de actuar. Estás decidiendo cuánta incertidumbre cargar.",
     "takeaway": "Reducir la concentración es una decisión de riesgo, no una predicción."
    },
    "leave": {
     "label": "Dejarla por ahora",
     "outcome": "Mantienes la posición y anotas por qué te sientes cómodo con la concentración. También eliges cuándo revisarla.",
     "takeaway": "Mantener una posición también merece un motivo pensado."
    }
   }
  },
  "the-cheap-share": {
   "title": "“Esa acción es más barata.”",
   "body": "Shark señala dos empresas ficticias: una acción cuesta 5 y la otra 100. “Cinco es una ganga, ¿no?”",
   "choices": {
    "compare": {
     "label": "Preguntar cuántas acciones existen",
     "outcome": "La empresa de precio 5 tiene muchísimas más acciones. El precio por acción no te decía qué negocio completo era más barato.",
     "takeaway": "El precio por acción y el valor de una empresa son cosas distintas."
    },
    "business": {
     "label": "Mirar los negocios",
     "outcome": "Pones las ganancias, la deuda y las expectativas junto al precio. Hay más trabajo por hacer antes de llamar ganga a cualquiera.",
     "takeaway": "Un precio por acción bajo no es un argumento de inversión."
    },
    "cheap": {
     "label": "Elegir el número más bajo",
     "outcome": "El precio bajo te llama la atención. Sal te acerca la cantidad de acciones: ese único número dejaba fuera casi toda la comparación.",
     "takeaway": "El número más pequeño no es automáticamente el mejor valor."
    }
   }
  },
  "the-friday-close": {
   "title": "Antes de cerrar la laptop.",
   "body": "Fue una semana ruidosa. Sal deja una nota vacía en tu escritorio. Tienes tiempo para una cosa útil.",
   "choices": {
    "review": {
     "label": "Revisar una decisión",
     "outcome": "Comparas tu motivo con lo que pasó. Un buen resultado puede venir de un proceso débil, y una decisión cuidadosa igual puede perder.",
     "takeaway": "Revisa el razonamiento, además del resultado."
    },
    "write": {
     "label": "Escribir el plan de la próxima semana",
     "outcome": "Anotas una empresa para investigar y una pregunta que todavía no puedes responder. El lunes ya tiene un punto de partida.",
     "takeaway": "Una pregunta sin respuesta puede ser un buen próximo paso."
    },
    "stop": {
     "label": "Tomarte la noche libre",
     "outcome": "Cierras el escritorio sin forzar una operación más. El mercado seguirá ahí cuando vuelvas.",
     "takeaway": "No necesitas una operación en cada visita."
    }
   }
  },
  "know-what-you-hold": {
   "title": "Misma empresa. Otro token.",
   "body": "Dos tokens siguen a la misma empresa. Sus nombres te resultan familiares. Oracle pone sus páginas de emisor una al lado de la otra.",
   "choices": {
    "rights": {
     "label": "Leer los términos del emisor",
     "outcome": "Las páginas describen derechos y vías de rescate distintos. Revisas el token en sí, no solo el nombre de la empresa.",
     "takeaway": "Un token vinculado a una acción no te da automáticamente todos los derechos de un accionista."
    },
    "market": {
     "label": "Comparar los mercados",
     "outcome": "Notas liquidez y precios distintos. Sumas los términos del emisor a tus revisiones antes de tratarlos como intercambiables.",
     "takeaway": "Importan la identidad de la empresa, los términos del token y las condiciones de negociación."
    },
    "logo": {
     "label": "Confiar en el logo igual",
     "outcome": "Los logos coinciden, pero los contratos y los términos no. Te detienes antes de suponer que las imágenes prueban que son equivalentes.",
     "takeaway": "Un logo conocido no verifica un activo."
    }
   }
  },
  "the-weekend-note": {
   "title": "Un escritorio más tranquilo.",
   "body": "Hoy no hay prisa. Sal te pide que elijas una cosa que quieras entender mejor antes del próximo día agitado.",
   "choices": {
    "company": {
     "label": "Cómo gana dinero una empresa",
     "outcome": "Haces una lista corta: quién paga, qué compra y cuánto cuesta entregarlo. Ya tienes un plan de investigación para tu próxima visita.",
     "takeaway": "Empieza por el negocio detrás del símbolo."
    },
    "risk": {
     "label": "Qué podría salir mal",
     "outcome": "Nombras un supuesto de tu plan y qué evidencia lo pondría en duda. La incertidumbre es más fácil de hablar cuando es concreta.",
     "takeaway": "Un riesgo es más útil cuando puedes explicarlo."
    },
    "journal": {
     "label": "En qué cambié de opinión",
     "outcome": "Relees un motivo antiguo y agregas lo que ahora ves distinto. Cambiar de opinión puede ser parte de un proceso cuidadoso.",
     "takeaway": "Lleva un registro de cómo cambia tu forma de pensar."
    }
   }
  }
 },
 "pt": {
  "the-group-chat": {
   "title": "O grupo está agitado.",
   "body": "Todo mundo está falando de Aster. “Vai subir”, diz Wolf. A captura de tela não tem fonte. Seu café nem esfriou ainda.",
   "choices": {
    "ask": {
     "label": "Pedir a fonte",
     "outcome": "Wolf manda a publicação original. Ela tem três meses. Você coloca a empolgação em pausa e abre a atualização da empresa.",
     "takeaway": "Uma captura de tela é um ponto de partida, não a história toda."
    },
    "wait": {
     "label": "Observar por um tempo",
     "outcome": "Você deixa Aster na sua lista de acompanhamento. Mais tarde, o grupo se acalma. Você manteve suas opções abertas sem fazer uma operação.",
     "takeaway": "Esperar também é uma decisão."
    },
    "follow": {
     "label": "Seguir a multidão",
     "outcome": "Nesta história, você entra correndo. Uma segunda mensagem contradiz a primeira. Agora você tem uma posição, mas nenhum motivo em que confie.",
     "takeaway": "Antes de seguir a multidão, anote o que faria você mudar de ideia."
    }
   }
  },
  "a-red-morning": {
   "title": "Uma manhã no vermelho.",
   "body": "Aster cai 6% nesta história da mesa. Sal deixa um bilhete ao lado da sua tela: “O preço mexeu. O que mais mudou?”",
   "choices": {
    "read": {
     "label": "Ler a atualização da empresa",
     "outcome": "A receita está estável, mas os custos subiram. Agora você tem um fato para comparar com seu plano original.",
     "takeaway": "Preço e desempenho do negócio são evidências diferentes."
    },
    "plan": {
     "label": "Abrir meu plano original",
     "outcome": "Seu bilhete diz que você revisaria depois dos próximos resultados. Você coloca a manchete ao lado desse plano antes de tomar uma nova decisão.",
     "takeaway": "Um plano dá algo a que voltar quando as emoções falam alto."
    },
    "panic": {
     "label": "Vender porque está no vermelho",
     "outcome": "Você reage à cor antes de ler a atualização. A história para aí: vender pode fazer parte de um plano, mas o vermelho sozinho não explica nenhum.",
     "takeaway": "Pergunte o que mudou antes de escolher como responder."
    }
   }
  },
  "one-big-position": {
   "title": "Uma posição muito grande.",
   "body": "Uma única empresa agora representa 70% da sua mesa fictícia. Oracle vira o monitor para você: “Uma boa semana deixou esta mesa bem desequilibrada.”",
   "choices": {
    "inspect": {
     "label": "Olhar a mesa inteira",
     "outcome": "Você compara quanto depende dessa única empresa. Um pequeno movimento ali poderia pesar mais que todo o resto.",
     "takeaway": "Olhe o tamanho da posição, além do desempenho."
    },
    "trim": {
     "label": "Pensar em reduzi-la",
     "outcome": "Você simula no papel uma posição menor antes de agir. Você está decidindo quanta incerteza carregar.",
     "takeaway": "Reduzir a concentração é uma decisão de risco, não uma previsão."
    },
    "leave": {
     "label": "Deixar como está por enquanto",
     "outcome": "Você mantém a posição e anota por que está confortável com a concentração. Você também escolhe quando revisá-la.",
     "takeaway": "Manter uma posição também merece um motivo pensado."
    }
   }
  },
  "the-cheap-share": {
   "title": "“Essa ação é mais barata.”",
   "body": "Shark aponta para duas empresas fictícias: uma ação custa 5 e a outra 100. “Cinco é uma pechincha, né?”",
   "choices": {
    "compare": {
     "label": "Perguntar quantas ações existem",
     "outcome": "A empresa de preço 5 tem muito mais ações. O preço da ação sozinho não dizia qual negócio inteiro era mais barato.",
     "takeaway": "O preço por ação e o valor de uma empresa são coisas diferentes."
    },
    "business": {
     "label": "Olhar os negócios",
     "outcome": "Você coloca lucros, dívidas e expectativas ao lado do preço. Ainda há trabalho a fazer antes de chamar qualquer uma de pechincha.",
     "takeaway": "Um preço de ação baixo não é um argumento de investimento."
    },
    "cheap": {
     "label": "Escolher o número menor",
     "outcome": "O preço baixo chama sua atenção. Sal mostra a quantidade de ações: esse único número deixava de fora quase toda a comparação.",
     "takeaway": "O menor número não é automaticamente o melhor valor."
    }
   }
  },
  "the-friday-close": {
   "title": "Antes de fechar o notebook.",
   "body": "Foi uma semana barulhenta. Sal deixa um bilhete em branco na sua mesa. Você tem tempo para uma coisa útil.",
   "choices": {
    "review": {
     "label": "Revisar uma decisão",
     "outcome": "Você compara seu motivo com o que aconteceu. Um bom resultado pode vir de um processo fraco, e uma decisão cuidadosa ainda pode perder.",
     "takeaway": "Revise o raciocínio, além do resultado."
    },
    "write": {
     "label": "Escrever o plano da próxima semana",
     "outcome": "Você anota uma empresa para pesquisar e uma pergunta que ainda não consegue responder. A segunda-feira agora tem um ponto de partida.",
     "takeaway": "Uma pergunta sem resposta pode ser um bom próximo passo."
    },
    "stop": {
     "label": "Tirar a noite de folga",
     "outcome": "Você fecha a mesa sem forçar mais uma operação. O mercado ainda vai estar lá quando você voltar.",
     "takeaway": "Você não precisa de uma operação a cada visita."
    }
   }
  },
  "know-what-you-hold": {
   "title": "Mesma empresa. Outro token.",
   "body": "Dois tokens acompanham a mesma empresa. Os nomes parecem familiares. Oracle coloca as páginas dos emissores lado a lado.",
   "choices": {
    "rights": {
     "label": "Ler os termos do emissor",
     "outcome": "As páginas descrevem direitos e formas de resgate diferentes. Você confere o próprio token, não só o nome da empresa.",
     "takeaway": "Um token ligado a uma ação não dá automaticamente todos os direitos de um acionista."
    },
    "market": {
     "label": "Comparar os mercados",
     "outcome": "Você nota liquidez e preços diferentes. Você inclui os termos do emissor nas suas verificações antes de tratá-los como intercambiáveis.",
     "takeaway": "Identidade da empresa, termos do token e condições de negociação, tudo isso importa."
    },
    "logo": {
     "label": "Confiar no logo igual",
     "outcome": "Os logos coincidem, mas os contratos e os termos não. Você para antes de supor que as imagens provam que são equivalentes.",
     "takeaway": "Um logo conhecido não verifica um ativo."
    }
   }
  },
  "the-weekend-note": {
   "title": "Uma mesa mais tranquila.",
   "body": "Sem pressa hoje. Sal pede que você escolha uma coisa que quer entender melhor antes do próximo dia agitado.",
   "choices": {
    "company": {
     "label": "Como uma empresa ganha dinheiro",
     "outcome": "Você faz uma lista curta: quem paga, o que compra e quanto custa entregar. Agora você tem um plano de pesquisa para a próxima visita.",
     "takeaway": "Comece pelo negócio por trás do código."
    },
    "risk": {
     "label": "O que pode dar errado",
     "outcome": "Você nomeia uma suposição do seu plano e que evidência a colocaria em dúvida. A incerteza fica mais fácil de discutir quando é específica.",
     "takeaway": "Um risco é mais útil quando você consegue explicá-lo."
    },
    "journal": {
     "label": "Em que mudei de ideia",
     "outcome": "Você relê um motivo antigo e acrescenta o que vê diferente agora. Mudar de ideia pode fazer parte de um processo cuidadoso.",
     "takeaway": "Registre como seu jeito de pensar muda."
    }
   }
  }
 },
 "fr": {
  "the-group-chat": {
   "title": "Le groupe de discussion s’agite.",
   "body": "Tout le monde parle d’Aster. « Ça va monter », dit Wolf. La capture d’écran n’a pas de source. Ton café n’a même pas refroidi.",
   "choices": {
    "ask": {
     "label": "Demander la source",
     "outcome": "Wolf envoie la publication d’origine. Elle date de trois mois. Tu mets l’enthousiasme en pause et tu ouvres la mise à jour de l’entreprise.",
     "takeaway": "Une capture d’écran est un point de départ, pas toute l’histoire."
    },
    "wait": {
     "label": "Observer un moment",
     "outcome": "Tu laisses Aster dans ta liste de suivi. Plus tard, le groupe se calme. Tu as gardé toutes tes options sans passer d’opération.",
     "takeaway": "Attendre, c’est aussi décider."
    },
    "follow": {
     "label": "Suivre la foule",
     "outcome": "Dans cette histoire, tu te précipites. Un deuxième message contredit le premier. Tu as maintenant une position, mais aucune raison à laquelle tu te fies.",
     "takeaway": "Avant de suivre la foule, note ce qui te ferait changer d’avis."
    }
   }
  },
  "a-red-morning": {
   "title": "Une matinée dans le rouge.",
   "body": "Aster recule de 6 % dans cette histoire du bureau. Sal pose un mot à côté de ton écran : « Le prix a bougé. Quoi d’autre a changé ? »",
   "choices": {
    "read": {
     "label": "Lire la mise à jour de l’entreprise",
     "outcome": "Le chiffre d’affaires est stable, mais les coûts ont augmenté. Tu as maintenant un fait à comparer avec ton plan de départ.",
     "takeaway": "Le prix et la performance de l’entreprise sont deux preuves différentes."
    },
    "plan": {
     "label": "Ouvrir mon plan de départ",
     "outcome": "Ta note dit que tu ferais le point après les prochains résultats. Tu poses le gros titre à côté de ce plan avant de prendre une nouvelle décision.",
     "takeaway": "Un plan te donne un repère quand les émotions s’emballent."
    },
    "panic": {
     "label": "Vendre parce que c’est rouge",
     "outcome": "Tu réagis à la couleur avant de lire la mise à jour. L’histoire s’arrête là : vendre peut faire partie d’un plan, mais le rouge seul n’en explique aucun.",
     "takeaway": "Demande-toi ce qui a changé avant de choisir ta réponse."
    }
   }
  },
  "one-big-position": {
   "title": "Une position très importante.",
   "body": "Une seule entreprise pèse désormais 70 % de ton bureau fictif. Oracle tourne l’écran vers toi : « Une bonne semaine a beaucoup déséquilibré ce bureau. »",
   "choices": {
    "inspect": {
     "label": "Regarder tout le bureau",
     "outcome": "Tu compares ce qui dépend de cette seule entreprise. Un petit mouvement de son côté pourrait désormais l’emporter sur tout le reste.",
     "takeaway": "Regarde la taille de la position, pas seulement sa performance."
    },
    "trim": {
     "label": "Envisager de l’alléger",
     "outcome": "Tu simules sur papier une position plus petite avant d’agir. Tu décides quelle part d’incertitude tu veux porter.",
     "takeaway": "Réduire la concentration est une décision de risque, pas une prédiction."
    },
    "leave": {
     "label": "La garder pour l’instant",
     "outcome": "Tu gardes la position et tu notes pourquoi cette concentration te convient. Tu choisis aussi quand la revoir.",
     "takeaway": "Garder une position mérite aussi une raison réfléchie."
    }
   }
  },
  "the-cheap-share": {
   "title": "« Cette action est moins chère. »",
   "body": "Shark montre deux entreprises fictives : une action coûte 5, l’autre 100. « Cinq, c’est une affaire, non ? »",
   "choices": {
    "compare": {
     "label": "Demander combien d’actions existent",
     "outcome": "L’entreprise à 5 a bien plus d’actions. Le prix de l’action seul ne disait pas quelle entreprise, dans son ensemble, était la moins chère.",
     "takeaway": "Le prix d’une action et la valeur d’une entreprise sont deux choses différentes."
    },
    "business": {
     "label": "Regarder les entreprises",
     "outcome": "Tu places les bénéfices, la dette et les attentes à côté du prix. Il reste du travail avant de parler d’une affaire pour l’une ou l’autre.",
     "takeaway": "Un prix d’action bas n’est pas un argument d’investissement."
    },
    "cheap": {
     "label": "Choisir le plus petit nombre",
     "outcome": "Le prix bas attire ton regard. Sal fait glisser le nombre d’actions vers toi : ce seul chiffre laissait de côté l’essentiel de la comparaison.",
     "takeaway": "Le plus petit nombre n’est pas forcément la meilleure valeur."
    }
   }
  },
  "the-friday-close": {
   "title": "Avant de fermer l’ordinateur.",
   "body": "La semaine a été agitée. Sal laisse un mot vierge sur ton bureau. Tu as le temps pour une chose utile.",
   "choices": {
    "review": {
     "label": "Revoir une décision",
     "outcome": "Tu compares ta raison avec ce qui s’est passé. Un bon résultat peut venir d’une démarche fragile, et une décision réfléchie peut quand même perdre.",
     "takeaway": "Revois le raisonnement, pas seulement le résultat."
    },
    "write": {
     "label": "Écrire le plan de la semaine prochaine",
     "outcome": "Tu notes une entreprise à étudier et une question à laquelle tu ne sais pas encore répondre. Lundi a maintenant un point de départ.",
     "takeaway": "Une question sans réponse peut être une bonne prochaine étape."
    },
    "stop": {
     "label": "Prendre la soirée",
     "outcome": "Tu fermes le bureau sans forcer une opération de plus. Le marché sera toujours là à ton retour.",
     "takeaway": "Tu n’as pas besoin d’une opération à chaque visite."
    }
   }
  },
  "know-what-you-hold": {
   "title": "Même entreprise. Autre token.",
   "body": "Deux tokens suivent la même entreprise. Leurs noms te semblent familiers. Oracle place les pages de leurs émetteurs côte à côte.",
   "choices": {
    "rights": {
     "label": "Lire les conditions de l’émetteur",
     "outcome": "Les pages décrivent des droits et des modalités de rachat différents. Tu vérifies le token lui-même, pas seulement le nom de l’entreprise.",
     "takeaway": "Un token lié à une action ne donne pas automatiquement tous les droits d’un actionnaire."
    },
    "market": {
     "label": "Comparer les marchés",
     "outcome": "Tu remarques des liquidités et des prix différents. Tu ajoutes les conditions de l’émetteur à tes vérifications avant de les considérer comme interchangeables.",
     "takeaway": "L’identité de l’entreprise, les conditions du token et les conditions de marché comptent toutes."
    },
    "logo": {
     "label": "Se fier au même logo",
     "outcome": "Les logos sont identiques, mais pas les contrats ni les conditions. Tu t’arrêtes avant de supposer que les images prouvent qu’ils se valent.",
     "takeaway": "Un logo familier ne vérifie pas un actif."
    }
   }
  },
  "the-weekend-note": {
   "title": "Un bureau plus calme.",
   "body": "Pas de précipitation aujourd’hui. Sal te demande de choisir une chose que tu veux mieux comprendre avant la prochaine journée chargée.",
   "choices": {
    "company": {
     "label": "Comment une entreprise gagne de l’argent",
     "outcome": "Tu dresses une courte liste : qui paie, ce qu’il achète et ce que coûte la livraison. Tu as un plan de recherche pour ta prochaine visite.",
     "takeaway": "Commence par l’entreprise derrière le symbole."
    },
    "risk": {
     "label": "Ce qui pourrait mal tourner",
     "outcome": "Tu nommes une hypothèse de ton plan et les preuves qui la remettraient en cause. L’incertitude se discute mieux quand elle est précise.",
     "takeaway": "Un risque est plus utile quand tu sais l’expliquer."
    },
    "journal": {
     "label": "Ce sur quoi j’ai changé d’avis",
     "outcome": "Tu relis une ancienne raison et tu ajoutes ce que tu vois autrement aujourd’hui. Changer d’avis peut faire partie d’une démarche réfléchie.",
     "takeaway": "Garde une trace de l’évolution de ta façon de penser."
    }
   }
  }
 }
};
