-- Apply as the same dedicated migration owner as 0001/0002.
-- Practice authentication is separate from X/financial provider_identities.
BEGIN;

CREATE TABLE trimmy.practice_auth_identities (
  provider text NOT NULL DEFAULT 'privy' CHECK (provider = 'privy'),
  app_id text COLLATE "C" NOT NULL CHECK (app_id ~ '^[A-Za-z0-9_-]{1,128}$'),
  subject text COLLATE "C" NOT NULL CHECK (subject ~ '^did:privy:[A-Za-z0-9]{1,128}$'),
  user_id uuid NOT NULL UNIQUE REFERENCES trimmy.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (app_id, subject)
);
ALTER TABLE trimmy.practice_auth_identities ENABLE ROW LEVEL SECURITY;
-- No runtime allow policies/table grants. Only the migration-owner definer
-- functions below can read/create mappings; the owner bypass is intentional.
REVOKE ALL ON TABLE trimmy.practice_auth_identities FROM PUBLIC;
CREATE TRIGGER practice_identity_immutable BEFORE UPDATE OR DELETE ON trimmy.practice_auth_identities
  FOR EACH ROW EXECUTE FUNCTION trimmy.reject_mutation();

CREATE FUNCTION trimmy.practice_find_account(verified_app_id text, verified_subject text) RETURNS uuid
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = pg_catalog, trimmy, pg_temp AS $$
DECLARE account_id uuid;
BEGIN
  IF verified_app_id IS NULL OR (verified_app_id COLLATE "C") !~ '^[A-Za-z0-9_-]{1,128}$'
      OR verified_subject IS NULL OR (verified_subject COLLATE "C") !~ '^did:privy:[A-Za-z0-9]{1,128}$' THEN
    RAISE EXCEPTION 'Verified practice identity is invalid' USING ERRCODE = '22023';
  END IF;
  SELECT m.user_id INTO account_id
    FROM trimmy.practice_auth_identities m JOIN trimmy.users u ON u.id = m.user_id
    WHERE m.app_id = verified_app_id AND m.subject = verified_subject AND u.status <> 'closed';
  RETURN account_id;
END;
$$;
REVOKE ALL ON FUNCTION trimmy.practice_find_account(text, text) FROM PUBLIC;

CREATE FUNCTION trimmy.practice_provision_account(verified_app_id text, verified_subject text) RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, trimmy, pg_temp AS $$
DECLARE account_id uuid; account_status text;
BEGIN
  IF verified_app_id IS NULL OR (verified_app_id COLLATE "C") !~ '^[A-Za-z0-9_-]{1,128}$'
      OR verified_subject IS NULL OR (verified_subject COLLATE "C") !~ '^did:privy:[A-Za-z0-9]{1,128}$' THEN
    RAISE EXCEPTION 'Verified practice identity is invalid' USING ERRCODE = '22023';
  END IF;
  -- Same identity provisions once. Hash collisions serialize unrelated callers
  -- but never change the exact, unique app/subject binding below.
  PERFORM pg_advisory_xact_lock(hashtextextended('trimmy.practice.identity:' || verified_app_id || ':' || verified_subject, 0));
  SELECT m.user_id, u.status INTO account_id, account_status
    FROM trimmy.practice_auth_identities m JOIN trimmy.users u ON u.id = m.user_id
    WHERE m.app_id = verified_app_id AND m.subject = verified_subject
    FOR UPDATE OF u;
  IF FOUND THEN
    IF account_status = 'closed' THEN RETURN NULL; END IF;
    RETURN account_id;
  END IF;
  -- UUID is generated by users' database default. Callers cannot choose, link,
  -- or replace it; a failed mapping insert also rolls back this account insert.
  INSERT INTO trimmy.users DEFAULT VALUES RETURNING id INTO account_id;
  INSERT INTO trimmy.practice_auth_identities(app_id, subject, user_id)
    VALUES (verified_app_id, verified_subject, account_id);
  RETURN account_id;
END;
$$;
REVOKE ALL ON FUNCTION trimmy.practice_provision_account(text, text) FROM PUBLIC;

-- Narrow grants for the separately provisioned trusted API runtime:
--   GRANT USAGE ON SCHEMA trimmy TO trimmy_practice_runtime;
--   GRANT EXECUTE ON FUNCTION trimmy.practice_find_account(text,text),
--     trimmy.practice_provision_account(text,text) TO trimmy_practice_runtime;
-- No users, mapping, provider_identities, or financial table grants; no schema
-- CREATE, superuser/BYPASSRLS or owner memberships. Fixed trusted search_path
-- and schema-qualified relations protect both definer functions from shadowing.
-- Arguments MUST come from server-verified Privy access-token output. SQL access
-- is a trusted server privilege, not proof that arbitrary supplied DIDs are real.
-- Keep functions off public RPC surfaces. No raw token or wallet metadata is stored.
-- One verified identity owns one practice UUID; account linking is not supported.
-- Closed mappings remain immutable and cannot silently create a fresh account.

INSERT INTO trimmy.schema_migrations(version) VALUES ('0003_practice_accounts');
COMMIT;
