BEGIN;
CREATE TABLE trimmy.workday_definitions (
 id text PRIMARY KEY, ordinal integer NOT NULL UNIQUE CHECK(ordinal>0), version text NOT NULL, payload jsonb NOT NULL
);
CREATE TRIGGER workday_definitions_immutable BEFORE UPDATE OR DELETE ON trimmy.workday_definitions FOR EACH ROW EXECUTE FUNCTION trimmy.reject_mutation();
CREATE TABLE trimmy.workday_attempts (
 user_id uuid NOT NULL REFERENCES trimmy.users(id), assignment_id text NOT NULL REFERENCES trimmy.workday_definitions(id),
 revision integer NOT NULL DEFAULT 0 CHECK(revision>=0), step integer NOT NULL DEFAULT 0 CHECK(step BETWEEN 0 AND 3),
 answers jsonb NOT NULL DEFAULT '{}', draft text NOT NULL DEFAULT '' CHECK(char_length(draft)<=280),
 updated_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(user_id,assignment_id)
);
CREATE TABLE trimmy.workday_completions (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES trimmy.users(id),
 assignment_id text NOT NULL REFERENCES trimmy.workday_definitions(id), artifact text NOT NULL,
 completed_at timestamptz NOT NULL, completed_date date NOT NULL, UNIQUE(user_id,assignment_id)
);
CREATE TRIGGER workday_completions_immutable BEFORE UPDATE OR DELETE ON trimmy.workday_completions FOR EACH ROW EXECUTE FUNCTION trimmy.reject_mutation();
ALTER TABLE trimmy.workday_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE trimmy.workday_attempts FORCE ROW LEVEL SECURITY;
ALTER TABLE trimmy.workday_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE trimmy.workday_completions FORCE ROW LEVEL SECURITY;
REVOKE ALL ON trimmy.workday_definitions,trimmy.workday_attempts,trimmy.workday_completions FROM PUBLIC;
ALTER TABLE trimmy.career_activity_events DROP CONSTRAINT career_activity_events_activity_kind_check;
ALTER TABLE trimmy.career_activity_events ADD CONSTRAINT career_activity_events_activity_kind_check CHECK(activity_kind IN ('paper-order','trade-reason','mission','daily-shift','workday'));
ALTER TABLE trimmy.career_trim_ledger DROP CONSTRAINT career_trim_ledger_kind_reward;
ALTER TABLE trimmy.career_trim_ledger ADD CONSTRAINT career_trim_ledger_kind_reward CHECK(
(entry_kind IN ('paper-reason','daily-shift') AND trims=10) OR (entry_kind IN ('mission','workday') AND trims=20) OR (entry_kind='promotion' AND trims=100));
INSERT INTO trimmy.workday_definitions VALUES ('morning-brief',1,'intern-2026-09-24.1',$work${"id":"morning-brief","ordinal":1,"title":"The morning brief","speaker":"sal","district":"First days","brief":"Aster’s update is in. Tell me what actually changed.","sourceTitle":"Aster · annual update","sourceLabel":"Office simulation","rows":[{"id":"before","label":"2024","value":"$1,000 sales · $600 costs","detail":"Profit is what remains after the costs shown."},{"id":"after","label":"2025","value":"$1,500 sales · $1,300 costs","detail":"Same company. Same currency. Compare the two periods."},{"id":"headline","label":"Draft headline","value":"A record year for profit","detail":"A headline is a claim. Check it against the figures."}],"evidence":{"prompt":"Pin the two periods you need to check profit.","requiredIds":["before","after"]},"decision":{"kind":"number","prompt":"What was Aster’s 2025 profit?","acceptedAnswers":["200"],"hint":"Subtract the 2025 costs from 2025 sales.","choices":[],"unit":"$"},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"Sales rose from $1,000 to $1,500."},{"id":"fact-2","text":"Profit fell from $400 to $200."},{"id":"fact-3","text":"Higher sales prove profit increased."}],"requiredIds":["fact-1","fact-2"]},"feedback":"Sales rose. Profit fell. You found the part the headline missed. Your brief is on my desk.","art":"newspaper"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('two-companies',2,'intern-2026-09-24.1',$work${"id":"two-companies","ordinal":2,"title":"Two companies, one call","speaker":"shark","district":"First days","brief":"Aster costs $5 a share. Helio costs $100. Which whole business has the smaller market value?","sourceTitle":"Two fictional companies","sourceLabel":"Office simulation","rows":[{"id":"aster","label":"Aster","value":"$5 × 10 million shares","detail":"Price multiplied by shares outstanding gives equity market value."},{"id":"helio","label":"Helio","value":"$100 × 100,000 shares","detail":"Use the same calculation for both companies."},{"id":"chat","label":"Shark’s message","value":"Five dollars looks cheap","detail":"Price per share is not the value of the whole business."}],"evidence":{"prompt":"Pin both companies for a fair comparison.","requiredIds":["aster","helio"]},"decision":{"kind":"choice","prompt":"Which has the smaller equity market value?","acceptedAnswers":["helio"],"hint":"Aster: $50 million. Helio: $10 million.","choices":[{"id":"aster","label":"Aster","feedback":"Count all the shares, not just the price of one."},{"id":"helio","label":"Helio","feedback":"Exactly: $100 × 100,000 = $10 million."},{"id":"equal","label":"They are equal","feedback":"Their share counts are different."}],"unit":null},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"Helio’s equity market value is $10 million."},{"id":"fact-2","text":"Aster’s is $50 million; share price alone cannot establish value."},{"id":"fact-3","text":"Aster must be cheaper because one share costs less."}],"requiredIds":["fact-1","fact-2"]},"feedback":"You compared whole businesses. That is a useful comparison—not a buy recommendation.","art":"balance"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('before-the-trade',3,'intern-2026-09-24.1',$work${"id":"before-the-trade","ordinal":3,"title":"Before the trade","speaker":"oracle","district":"First days","brief":"You have a possible idea. Decide how much room it deserves before pressing Buy.","sourceTitle":"Your fictional risk plan","sourceLabel":"Office simulation","rows":[{"id":"cash","label":"Desk cash","value":"$1,000","detail":"This is an authored planning example, not your live balance."},{"id":"loss","label":"Loss budget","value":"$20","detail":"This is the largest planned loss for this one idea."},{"id":"move","label":"Review distance","value":"5% below entry","detail":"For this exercise, calculate 5% of the position. Gaps could make a real loss larger."}],"evidence":{"prompt":"Pin the loss budget and review distance.","requiredIds":["loss","move"]},"decision":{"kind":"number","prompt":"What position size gives a planned 5% loss of $20?","acceptedAnswers":["400"],"hint":"$20 divided by 0.05 is the position size. This is a plan, not a guarantee.","choices":[],"unit":"$"},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"A $400 position has a planned $20 loss at a 5% move."},{"id":"fact-2","text":"A gap or execution delay could make the actual loss larger."},{"id":"fact-3","text":"A review price guarantees a $20 maximum loss."}],"requiredIds":["fact-1","fact-2"]},"feedback":"The size follows the plan. Keep the uncertainty in the note too.","art":"calculator"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('missing-costs',4,'intern-2026-09-24.1',$work${"id":"missing-costs","ordinal":4,"title":"A teammate needs a hand","speaker":"wolf","district":"First days","brief":"I’ve got the sales numbers. Can you send Sal an update?","sourceTitle":"Wolf’s unfinished update","sourceLabel":"Office simulation","rows":[{"id":"sales","label":"Sales","value":"$1,800 → $2,400","detail":"These figures compare last year with this year."},{"id":"costs","label":"Costs","value":"Not attached","detail":"You cannot calculate profit without costs."},{"id":"draft","label":"Wolf’s draft","value":"Profit is growing fast","detail":"This goes beyond the information supplied."}],"evidence":{"prompt":"Pin the evidence and the missing information.","requiredIds":["sales","costs"]},"decision":{"kind":"choice","prompt":"How do you move this forward?","acceptedAnswers":["ask","qualify"],"hint":"You can request the missing costs or send a carefully limited sales-only update.","choices":[{"id":"ask","label":"Ask Wolf for the costs","feedback":"Wolf is getting the missing cost report for you."},{"id":"qualify","label":"Send a sales-only update","feedback":"Your update clearly says profit is still unknown."},{"id":"approve","label":"Send Wolf’s draft","feedback":"The draft makes a profit claim the figures cannot support."}],"unit":null},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"Sales increased from $1,800 to $2,400."},{"id":"fact-2","text":"Profit cannot be assessed from this update alone."},{"id":"fact-3","text":"Profit must have risen with sales."}],"requiredIds":["fact-1","fact-2"]},"feedback":"Good. You kept the claim inside what the evidence can support. Wolf will follow up.","art":"mailbox"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('the-follow-up',5,'intern-2026-09-24.1',$work${"id":"the-follow-up","ordinal":5,"title":"The follow-up","speaker":"sal","district":"First days","brief":"The costs are here. Revisit the update you prepared with Wolf.","sourceTitle":"Wolf’s returned figures","sourceLabel":"Office simulation","rows":[{"id":"old","label":"Earlier period","value":"$1,800 sales · $1,300 costs","detail":"Earlier profit was $500."},{"id":"new","label":"Latest period","value":"$2,400 sales · $2,200 costs","detail":"Latest profit is sales minus costs."},{"id":"note","label":"Source","value":"Returned cost report","detail":"This is the information missing from the earlier update."}],"evidence":{"prompt":"Pin the two comparable periods.","requiredIds":["old","new"]},"decision":{"kind":"choice","prompt":"What changes in your update?","acceptedAnswers":["revise"],"hint":"Latest profit is $200, down from $500.","choices":[{"id":"revise","label":"Add the profit decline","feedback":"Your revised brief now includes the missing costs."},{"id":"ignore","label":"Keep the earlier claim","feedback":"New evidence should change an unsupported claim."},{"id":"double","label":"Say profit doubled","feedback":"The new figures show the opposite."}],"unit":null},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"Sales rose while profit fell from $500 to $200."},{"id":"fact-2","text":"The new cost evidence changes the assessment."},{"id":"fact-3","text":"The old profit claim still holds."}],"requiredIds":["fact-1","fact-2"]},"feedback":"You returned to the evidence and updated your view. That is the job. First week filed.","art":"reports","context":{"fromId":"missing-costs","responses":{"ask":"You asked Wolf for costs. He has sent the report.","qualify":"You filed a sales-only update. Wolf has now sent the missing costs."}}}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('fees-add-up',6,'intern-2026-09-24.1',$work${"id":"fees-add-up","ordinal":6,"title":"The small print adds up","speaker":"shark","district":"On the floor","brief":"This trade made a dollar before fees. Check what the desk actually kept.","sourceTitle":"A fictional trade receipt","sourceLabel":"Office simulation","rows":[{"id":"buy","label":"Purchase","value":"10 shares at $10","detail":"The shares cost $100 before fees."},{"id":"sell","label":"Sale","value":"10 shares at $10.10","detail":"The shares sold for $101 before fees."},{"id":"fees","label":"Fees","value":"$1 to buy + $1 to sell","detail":"Include both sides when calculating the result."}],"evidence":{"prompt":"Pin the sale and total fee evidence.","requiredIds":["sell","fees"]},"decision":{"kind":"number","prompt":"What is the net result after both fees?","acceptedAnswers":["-1"],"hint":"$101 minus $100 minus $2 = -$1.","choices":[],"unit":"$"},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"The trade gained $1 before fees."},{"id":"fact-2","text":"After $2 in fees, the result was a $1 loss."},{"id":"fact-3","text":"A green price move always means a net gain."}],"requiredIds":["fact-1","fact-2"]},"feedback":"You reconciled the receipt. Small fees can change the result of a small move.","art":"safe"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('share-split',7,'intern-2026-09-24.1',$work${"id":"share-split","ordinal":7,"title":"More shares, same slice","speaker":"sal","district":"On the floor","brief":"A split changed the share count. Did it change your ownership?","sourceTitle":"A 10-for-1 split","sourceLabel":"Office simulation","rows":[{"id":"before","label":"Before","value":"1 share at $100","detail":"The company had 100 shares total."},{"id":"after","label":"After","value":"10 shares at $10","detail":"The company now has 1,000 shares total."},{"id":"claim","label":"Desk chat","value":"Ten times richer?","detail":"The count changed. Check the fraction and total value."}],"evidence":{"prompt":"Pin the before and after records.","requiredIds":["before","after"]},"decision":{"kind":"choice","prompt":"What happened to your ownership fraction?","acceptedAnswers":["same"],"hint":"1/100 and 10/1,000 are both 1%.","choices":[{"id":"more","label":"Ten times larger","feedback":"The company’s total share count increased too."},{"id":"same","label":"It stayed the same","feedback":"Both fractions are 1%."},{"id":"less","label":"Ten times smaller","feedback":"Your share count also rose tenfold."}],"unit":null},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"The holding remains worth $100 in this example."},{"id":"fact-2","text":"Ownership stays at 1% immediately after the split."},{"id":"fact-3","text":"The split alone made the holding ten times more valuable."}],"requiredIds":["fact-1","fact-2"]},"feedback":"Different number of slices. Same slice of the business.","art":"folders"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('thin-market',8,'intern-2026-09-24.1',$work${"id":"thin-market","ordinal":8,"title":"A thin market","speaker":"oracle","district":"On the floor","brief":"The screen price looks good. The quote tells a different story.","sourceTitle":"Two executable-size previews","sourceLabel":"Office simulation","rows":[{"id":"small","label":"Small order","value":"$100 → 49.5 tokens","detail":"Estimated average price: about $2.02 per token."},{"id":"large","label":"Large order","value":"$1,000 → 450 tokens","detail":"Estimated average price: about $2.22 per token."},{"id":"last","label":"Last traded price","value":"$2.00","detail":"A last trade does not promise the price for your size."}],"evidence":{"prompt":"Pin both order-size quotes.","requiredIds":["small","large"]},"decision":{"kind":"choice","prompt":"What is a defensible next step?","acceptedAnswers":["smaller","wait"],"hint":"The larger order moves through worse prices. You can reduce size or wait.","choices":[{"id":"smaller","label":"Investigate a smaller order","feedback":"A smaller size may reduce price impact; check a fresh quote."},{"id":"wait","label":"Wait for better liquidity","feedback":"Waiting is a valid decision; no order was placed."},{"id":"force","label":"Assume $2 for all of it","feedback":"The size-specific quote contradicts that assumption."}],"unit":null},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"The larger order has a worse average quoted price."},{"id":"fact-2","text":"A displayed last price is not a guaranteed fill."},{"id":"fact-3","text":"Every order will fill at the last traded price."}],"requiredIds":["fact-1","fact-2"]},"feedback":"You checked the price for the size you wanted. That matters more than a green number.","art":"ticker"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('old-news',9,'intern-2026-09-24.1',$work${"id":"old-news","ordinal":9,"title":"Yesterday’s headline","speaker":"wolf","district":"On the floor","brief":"This post is everywhere. Before I share it, check whether it is new.","sourceTitle":"An update moving through the chat","sourceLabel":"Office simulation","rows":[{"id":"post","label":"Repost date","value":"24 September 2026","detail":"The post appeared today."},{"id":"source","label":"Original report","value":"18 April 2026","detail":"The figures describe the prior reporting period."},{"id":"caption","label":"Caption","value":"Breaking growth news","detail":"A new repost does not make the underlying evidence new."}],"evidence":{"prompt":"Pin the repost date and original report date.","requiredIds":["post","source"]},"decision":{"kind":"choice","prompt":"How should the update be described?","acceptedAnswers":["old"],"hint":"Use the original source date, not the date of a repost.","choices":[{"id":"new","label":"Fresh company news","feedback":"The source itself is older."},{"id":"old","label":"An older report being shared again","feedback":"That keeps the two dates clear."},{"id":"fake","label":"Definitely fabricated","feedback":"Age alone does not prove fabrication."}],"unit":null},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"The post is new, but the report is from April."},{"id":"fact-2","text":"Check for a newer report before treating it as a fresh update."},{"id":"fact-3","text":"A September repost makes April’s figures current."}],"requiredIds":["fact-1","fact-2"]},"feedback":"Source checked. You stopped old information from dressing up as a new event.","art":"clock"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('whole-desk',10,'intern-2026-09-24.1',$work${"id":"whole-desk","ordinal":10,"title":"Look at the whole desk","speaker":"oracle","district":"On the floor","brief":"One good run changed the shape of this portfolio. Show me where its risk sits.","sourceTitle":"A fictional $1,000 portfolio","sourceLabel":"Office simulation","rows":[{"id":"aster","label":"Aster","value":"$700","detail":"One issuer dominates this example."},{"id":"helio","label":"Helio","value":"$200","detail":"A second company."},{"id":"cash","label":"Cash","value":"$100","detail":"Cash is included in the total."}],"evidence":{"prompt":"Pin the largest position and the cash reserve.","requiredIds":["aster","cash"]},"decision":{"kind":"number","prompt":"What percentage of the desk is in Aster?","acceptedAnswers":["70"],"hint":"$700 divided by $1,000, multiplied by 100.","choices":[],"unit":"%"},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"Aster represents 70% of the portfolio."},{"id":"fact-2","text":"A move in Aster could dominate the desk’s result."},{"id":"fact-3","text":"Three lines on a portfolio mean equal diversification."}],"requiredIds":["fact-1","fact-2"]},"feedback":"You found the concentration. Now it can be discussed rather than hidden in a total.","art":"chart-board"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('what-you-own',11,'intern-2026-09-24.1',$work${"id":"what-you-own","ordinal":11,"title":"What do you actually own?","speaker":"sal","district":"Your own calls","brief":"Two products use the same company logo. Compare the terms before treating them alike.","sourceTitle":"Fictional issuer term cards","sourceLabel":"Office simulation","rows":[{"id":"one","label":"Token A","value":"Price exposure · no voting","detail":"Redemption is subject to issuer eligibility."},{"id":"two","label":"Token B","value":"Fund interest · stated redemption window","detail":"Different legal structure and terms."},{"id":"logo","label":"Same logo","value":"Same reference company","detail":"Company identity does not prove identical holder rights."}],"evidence":{"prompt":"Pin both issuer term cards.","requiredIds":["one","two"]},"decision":{"kind":"choice","prompt":"What can you conclude?","acceptedAnswers":["different"],"hint":"The issuer terms—not the logo—describe the holder’s rights.","choices":[{"id":"same","label":"They must grant the same rights","feedback":"The supplied term cards differ."},{"id":"different","label":"The exposure is related; the rights differ","feedback":"Keep the issuer and terms attached to the instrument."},{"id":"vote","label":"Both grant voting rights","feedback":"Token A explicitly says it does not."}],"unit":null},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"Both products reference the same company."},{"id":"fact-2","text":"Their rights and redemption terms differ."},{"id":"fact-3","text":"A matching logo guarantees ordinary shareholder rights."}],"requiredIds":["fact-1","fact-2"]},"feedback":"You separated the company from the instrument used to get exposure.","art":"exchange"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('mint-check',12,'intern-2026-09-24.1',$work${"id":"mint-check","ordinal":12,"title":"The right address","speaker":"shark","district":"Your own calls","brief":"A convincing logo came with a new address. Check the identity before the desk uses it.","sourceTitle":"A fictional asset identity check","sourceLabel":"Office simulation","rows":[{"id":"issuer","label":"Issuer registry","value":"Mint: ASTER-VERIFIED-01","detail":"Illustrative identifiers; these are not real on-chain addresses."},{"id":"listing","label":"Shared listing","value":"Mint: ASTER-VERlFIED-01","detail":"Look closely: one character differs."},{"id":"logo","label":"Listing artwork","value":"A familiar company logo","detail":"Artwork can be copied."}],"evidence":{"prompt":"Pin the registry identifier and listing identifier.","requiredIds":["issuer","listing"]},"decision":{"kind":"choice","prompt":"What should happen next?","acceptedAnswers":["verify"],"hint":"The strings differ. A logo is not evidence of contract identity.","choices":[{"id":"verify","label":"Pause and verify the exact mint","feedback":"The mismatch needs resolution."},{"id":"trust","label":"Trust the logo","feedback":"The logo does not resolve the mismatch."},{"id":"guess","label":"Choose whichever has more followers","feedback":"Popularity does not verify this contract."}],"unit":null},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"The listing identifier does not match the registry."},{"id":"fact-2","text":"Pause and verify the exact contract before using it."},{"id":"fact-3","text":"A familiar image is enough to establish identity."}],"requiredIds":["fact-1","fact-2"]},"feedback":"You caught the mismatch before it became an order.","art":"magnifier"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('spread',13,'intern-2026-09-24.1',$work${"id":"spread","ordinal":13,"title":"Two sides of a quote","speaker":"oracle","district":"Your own calls","brief":"A bid and an ask are not the same price. Work out the cost of crossing the spread.","sourceTitle":"A simplified two-sided market","sourceLabel":"Office simulation","rows":[{"id":"bid","label":"Best bid","value":"$9.90","detail":"The displayed price to sell immediately at this size."},{"id":"ask","label":"Best ask","value":"$10.10","detail":"The displayed price to buy immediately at this size."},{"id":"mid","label":"Midpoint","value":"$10.00","detail":"The midpoint is not necessarily an executable price."}],"evidence":{"prompt":"Pin the bid and ask.","requiredIds":["bid","ask"]},"decision":{"kind":"number","prompt":"What is the spread per share?","acceptedAnswers":["0.2","0.20"],"hint":"Ask minus bid: $10.10 − $9.90.","choices":[],"unit":"$"},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"The spread is $0.20 per share."},{"id":"fact-2","text":"The midpoint alone does not tell you the execution price."},{"id":"fact-3","text":"Buying and selling immediately both happen at $10.00."}],"requiredIds":["fact-1","fact-2"]},"feedback":"You can now explain the gap before a trade starts.","art":"bridge"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('dilution',14,'intern-2026-09-24.1',$work${"id":"dilution","ordinal":14,"title":"A bigger share count","speaker":"sal","district":"Your own calls","brief":"A company issued new shares. Recalculate the slice held by an existing owner.","sourceTitle":"New shares issued","sourceLabel":"Office simulation","rows":[{"id":"held","label":"Your holding","value":"10 shares","detail":"Your own number of shares did not change."},{"id":"old","label":"Old total","value":"100 shares","detail":"Your earlier ownership was 10%."},{"id":"new","label":"New total","value":"125 shares","detail":"Assume all shares have equal ownership rights."}],"evidence":{"prompt":"Pin the holding and new total.","requiredIds":["held","new"]},"decision":{"kind":"number","prompt":"What is the new ownership percentage?","acceptedAnswers":["8"],"hint":"10 divided by 125, multiplied by 100.","choices":[],"unit":"%"},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"Ownership changed from 10% to 8%."},{"id":"fact-2","text":"The holding’s share count stayed at 10."},{"id":"fact-3","text":"An unchanged share count guarantees unchanged ownership."}],"requiredIds":["fact-1","fact-2"]},"feedback":"The denominator matters. You explained the change without inventing a price prediction.","art":"skyscraper"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('second-hand-off',15,'intern-2026-09-24.1',$work${"id":"second-hand-off","ordinal":15,"title":"Send the useful version","speaker":"wolf","district":"Your own calls","brief":"I need the week’s checks in one short hand-off. Help me leave out the claims we cannot defend.","sourceTitle":"The team’s checked notes","sourceLabel":"Office simulation","rows":[{"id":"rights","label":"Instrument","value":"Issuer terms differ","detail":"Same company does not imply identical token rights."},{"id":"identity","label":"Identity","value":"Contract must match the registry","detail":"A logo alone does not verify a mint."},{"id":"promise","label":"Unverified claim","value":"A famous company cannot lose value","detail":"No source supports a guaranteed outcome."}],"evidence":{"prompt":"Pin the two supported checks.","requiredIds":["rights","identity"]},"decision":{"kind":"choice","prompt":"What belongs in the hand-off?","acceptedAnswers":["checks"],"hint":"Use the checks backed by evidence; leave out the guarantee.","choices":[{"id":"checks","label":"Terms, identity and order-size quote","feedback":"Those are concrete checks."},{"id":"promise","label":"The guaranteed-return claim","feedback":"The evidence offers no guarantee."},{"id":"logo","label":"Only the company logos","feedback":"Pictures omit the important distinctions."}],"unit":null},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"Check the issuer’s terms and exact contract identity."},{"id":"fact-2","text":"Use the quote for the actual order size."},{"id":"fact-3","text":"Familiar companies guarantee a positive return."}],"requiredIds":["fact-1","fact-2"]},"feedback":"Clear, short and useful. The next person can act on the checks you actually made.","art":"conference"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('drawdown',16,'intern-2026-09-24.1',$work${"id":"drawdown","ordinal":16,"title":"Getting back to even","speaker":"shark","district":"The bigger picture","brief":"This position fell from $100 to $80. Is a 20% gain enough to recover?","sourceTitle":"A fictional position","sourceLabel":"Office simulation","rows":[{"id":"start","label":"Starting value","value":"$100","detail":"Use this to understand the original loss."},{"id":"now","label":"Current value","value":"$80","detail":"A recovery percentage uses the current value as its base."},{"id":"gap","label":"Amount to recover","value":"$20","detail":"Compare this with $80, not $100."}],"evidence":{"prompt":"Pin the current value and recovery amount.","requiredIds":["now","gap"]},"decision":{"kind":"number","prompt":"What gain from $80 gets back to $100?","acceptedAnswers":["25"],"hint":"$20 divided by $80 is 25%.","choices":[],"unit":"%"},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"A 20% decline requires a 25% gain to recover."},{"id":"fact-2","text":"The percentage base changes after the loss."},{"id":"fact-3","text":"A 20% gain always cancels a 20% decline."}],"requiredIds":["fact-1","fact-2"]},"feedback":"You used the right base. Same dollar gap, different percentage.","art":"bull"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('sample-check',17,'intern-2026-09-24.1',$work${"id":"sample-check","ordinal":17,"title":"Who did we ask?","speaker":"sal","district":"The bigger picture","brief":"The team says everyone loves Aster. Read the trial results and fix the claim.","sourceTitle":"Product trial replies","sourceLabel":"Office simulation","rows":[{"id":"group","label":"People asked","value":"10 invited beta testers","detail":"They were selected for a product trial."},{"id":"yes","label":"Positive replies","value":"8 of 10","detail":"Two testers did not like the product."},{"id":"outside","label":"Other customers","value":"Not surveyed","detail":"The trial cannot speak for all customers."}],"evidence":{"prompt":"Pin the group definition and positive count.","requiredIds":["group","yes"]},"decision":{"kind":"choice","prompt":"Which wording fits the evidence?","acceptedAnswers":["sample"],"hint":"Keep both the count and the group in the statement.","choices":[{"id":"everyone","label":"Everyone loves it","feedback":"Other customers were not surveyed."},{"id":"sample","label":"8 of 10 beta testers liked it","feedback":"That names the count and the group."},{"id":"all","label":"All beta testers liked it","feedback":"Two of the ten did not."}],"unit":null},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"8 of 10 invited beta testers liked the product."},{"id":"fact-2","text":"The trial does not establish what all customers think."},{"id":"fact-3","text":"Everyone likes the product."}],"requiredIds":["fact-1","fact-2"]},"feedback":"A small result can still be useful when its limits travel with it.","art":"headset"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('cash-buffer',18,'intern-2026-09-24.1',$work${"id":"cash-buffer","ordinal":18,"title":"Leave room to breathe","speaker":"oracle","district":"The bigger picture","brief":"This desk needs a cash reserve. Work out how much is available for the proposed idea.","sourceTitle":"A fictional desk budget","sourceLabel":"Office simulation","rows":[{"id":"cash","label":"Available cash","value":"$1,200","detail":"There are no pending orders in this exercise."},{"id":"reserve","label":"Required reserve","value":"$300","detail":"Keep this available after the order."},{"id":"fees","label":"Estimated fees","value":"$10","detail":"Fees also come out of cash."}],"evidence":{"prompt":"Pin the required reserve and fee allowance.","requiredIds":["reserve","fees"]},"decision":{"kind":"number","prompt":"What is the largest purchase before fees that keeps the reserve?","acceptedAnswers":["890"],"hint":"$1,200 − $300 − $10.","choices":[],"unit":"$"},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"The maximum purchase is $890 before fees."},{"id":"fact-2","text":"That leaves $300 after the $10 fee."},{"id":"fact-3","text":"All $1,200 is available for the purchase."}],"requiredIds":["fact-1","fact-2"]},"feedback":"The plan includes what happens after the button is pressed.","art":"plant"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('change-your-mind',19,'intern-2026-09-24.1',$work${"id":"change-your-mind","ordinal":19,"title":"The plan meets new evidence","speaker":"wolf","district":"The bigger picture","brief":"Our old note assumed costs would stay flat. The new update challenges that. What do we do with the note?","sourceTitle":"A plan and a later update","sourceLabel":"Office simulation","rows":[{"id":"plan","label":"Earlier plan","value":"Review if operating costs rise over 10%","detail":"The review trigger was written before this update."},{"id":"update","label":"New costs","value":"$500 → $600","detail":"Costs rose by $100 from a $500 base."},{"id":"price","label":"Price today","value":"Up 3%","detail":"A short-term price move does not erase the plan’s trigger."}],"evidence":{"prompt":"Pin the original trigger and the new cost figures.","requiredIds":["plan","update"]},"decision":{"kind":"choice","prompt":"What does the plan call for?","acceptedAnswers":["review"],"hint":"Costs rose 20%, crossing the plan’s 10% review trigger.","choices":[{"id":"review","label":"Review the case against the new costs","feedback":"A review is due; buying or selling is a separate decision."},{"id":"ignore","label":"Ignore it because the price rose","feedback":"That replaces evidence with a short-term price move."},{"id":"panic","label":"Sell automatically without reading","feedback":"The plan calls for review, not an automatic sale."}],"unit":null},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"Costs rose 20%, so the review trigger was reached."},{"id":"fact-2","text":"Reassess the case; a review does not prescribe an automatic trade."},{"id":"fact-3","text":"A green price means the earlier trigger can be ignored."}],"requiredIds":["fact-1","fact-2"]},"feedback":"You followed a rule you wrote before the noise. Now make a fresh judgment.","art":"pencil"}$work$::jsonb);
INSERT INTO trimmy.workday_definitions VALUES ('first-desk-review',20,'intern-2026-09-24.1',$work${"id":"first-desk-review","ordinal":20,"title":"Your first desk review","speaker":"sal","district":"The bigger picture","brief":"Bring me a decision you can explain: the evidence, the limit, and what would change your mind.","sourceTitle":"Your first month’s hand-off","sourceLabel":"Office simulation","rows":[{"id":"evidence","label":"Evidence","value":"A dated source and checked figures","detail":"Separate what was observed from what was assumed."},{"id":"risk","label":"Risk","value":"A position size and review trigger","detail":"A plan describes uncertainty; it cannot remove it."},{"id":"outcome","label":"Outcome","value":"One result from one decision","detail":"A single gain or loss does not prove a process is sound."}],"evidence":{"prompt":"Pin the evidence and risk-plan requirements.","requiredIds":["evidence","risk"]},"decision":{"kind":"choice","prompt":"What makes a useful decision record?","acceptedAnswers":["process"],"hint":"A useful record can be checked and revisited even when the outcome disappoints.","choices":[{"id":"profit","label":"Only the final profit number","feedback":"The result omits how the decision was made."},{"id":"process","label":"Evidence, limits and a reason to revisit","feedback":"Someone else can understand and review that record."},{"id":"certainty","label":"A promise that the idea will work","feedback":"No decision record can guarantee the market’s response."}],"unit":null},"file":{"prompt":"File your update","parts":[{"id":"fact-1","text":"Keep the evidence, assumptions and review trigger together."},{"id":"fact-2","text":"Judge the process as well as the outcome."},{"id":"fact-3","text":"A profitable result proves every part of the decision was right."}],"requiredIds":["fact-1","fact-2"]},"feedback":"That is a desk I can hand work to. Your first twenty assignments are filed, and your decisions have a record.","art":"trophy"}$work$::jsonb);
CREATE OR REPLACE FUNCTION trimmy.check_career_activity_source() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, trimmy, pg_temp AS $$
DECLARE selected_user uuid; selected_kind text; selected_source uuid; selected_at timestamptz;
BEGIN
  IF TG_TABLE_NAME = 'career_activity_events' THEN
    selected_user := NEW.user_id;
    selected_kind := NEW.activity_kind;
    selected_source := NEW.source_id;
    selected_at := NEW.observed_at;
  ELSIF TG_TABLE_NAME = 'paper_orders' THEN
    selected_user := NEW.user_id; selected_kind := 'paper-order';
    selected_source := NEW.id; selected_at := NEW.committed_at;
  ELSIF TG_TABLE_NAME = 'career_trade_reasons' THEN
    selected_user := NEW.user_id; selected_kind := 'trade-reason';
    selected_source := NEW.order_id; selected_at := NEW.saved_at;
  ELSIF TG_TABLE_NAME = 'workday_completions' THEN
    selected_user := NEW.user_id; selected_kind := 'workday';
    selected_source := NEW.id; selected_at := NEW.completed_at;
  ELSIF TG_TABLE_NAME = 'daily_desk_shifts' THEN
    selected_user := NEW.user_id; selected_kind := 'daily-shift';
    selected_source := NEW.id; selected_at := NEW.completed_at;
  ELSE
    selected_user := NEW.user_id; selected_kind := 'mission';
    selected_source := NEW.completion_id; selected_at := NEW.completed_at;
  END IF;
  IF selected_kind = 'paper-order' THEN
    IF NOT EXISTS (SELECT 1 FROM trimmy.paper_orders o
      WHERE o.user_id = selected_user AND o.id = selected_source
        AND o.committed_at = selected_at) THEN
      RAISE EXCEPTION 'Career paper activity requires its order'
        USING ERRCODE = '23514', CONSTRAINT = 'career_activity_source_pair';
    END IF;
  ELSIF selected_kind = 'trade-reason' THEN
    IF NOT EXISTS (SELECT 1 FROM trimmy.career_trade_reasons r
      WHERE r.user_id = selected_user AND r.order_id = selected_source
        AND r.saved_at = selected_at) THEN
      RAISE EXCEPTION 'Career reason activity requires its reason'
        USING ERRCODE = '23514', CONSTRAINT = 'career_activity_source_pair';
    END IF;
  ELSIF selected_kind = 'mission' THEN
    IF NOT EXISTS (SELECT 1 FROM trimmy.career_mission_completions c
      WHERE c.user_id = selected_user AND c.completion_id = selected_source
        AND c.completed_at = selected_at) THEN
      RAISE EXCEPTION 'Career mission activity requires its completion'
        USING ERRCODE = '23514', CONSTRAINT = 'career_activity_source_pair';
    END IF;
  ELSIF selected_kind = 'workday' THEN
    IF NOT EXISTS (SELECT 1 FROM trimmy.workday_completions c WHERE c.user_id=selected_user AND c.id=selected_source AND c.completed_at=selected_at) THEN RAISE EXCEPTION 'Workday activity requires its filed work' USING ERRCODE='23514'; END IF;
  ELSIF selected_kind = 'daily-shift' THEN
    IF NOT EXISTS (SELECT 1 FROM trimmy.daily_desk_shifts s WHERE s.user_id=selected_user AND s.id=selected_source AND s.completed_at=selected_at) THEN RAISE EXCEPTION 'Daily activity requires its shift' USING ERRCODE='23514'; END IF;
  ELSE
    RAISE EXCEPTION 'Career activity kind is invalid'
      USING ERRCODE = '23514', CONSTRAINT = 'career_activity_source_pair';
  END IF;
  IF TG_TABLE_NAME <> 'career_activity_events' AND NOT EXISTS (
    SELECT 1 FROM trimmy.career_activity_events e
    WHERE e.user_id = selected_user AND e.activity_kind = selected_kind
      AND e.source_id = selected_source AND e.observed_at = selected_at
  ) THEN
    RAISE EXCEPTION 'Career activity source requires its event'
      USING ERRCODE = '23514', CONSTRAINT = 'career_activity_source_pair';
  END IF;
  RETURN NULL;
END;
$$;


CREATE CONSTRAINT TRIGGER workday_activity_pair AFTER INSERT ON trimmy.workday_completions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION trimmy.check_career_activity_source();
CREATE FUNCTION trimmy.check_workday_reward() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,trimmy,pg_temp AS $$
BEGIN
 IF TG_TABLE_NAME='workday_completions' THEN
  IF NOT EXISTS(SELECT 1 FROM trimmy.career_trim_ledger l WHERE l.user_id=NEW.user_id AND l.entry_kind='workday' AND l.source_id=NEW.id AND l.trims=20 AND l.awarded_on=NEW.completed_date AND l.created_at=NEW.completed_at) THEN RAISE EXCEPTION 'Filed work requires its reward' USING ERRCODE='23514'; END IF;
  IF NOT EXISTS(SELECT 1 FROM trimmy.workday_attempts a WHERE a.user_id=NEW.user_id AND a.assignment_id=NEW.assignment_id AND a.step=3) THEN RAISE EXCEPTION 'Filed work requires its completed attempt' USING ERRCODE='23514'; END IF;
 ELSIF NEW.entry_kind='workday' AND NOT EXISTS(SELECT 1 FROM trimmy.workday_completions c WHERE c.user_id=NEW.user_id AND c.id=NEW.source_id AND c.completed_date=NEW.awarded_on AND c.completed_at=NEW.created_at) THEN
  RAISE EXCEPTION 'Workday reward requires filed work' USING ERRCODE='23514';
 END IF;
 RETURN NULL;
END; $$;
REVOKE ALL ON FUNCTION trimmy.check_workday_reward() FROM PUBLIC;
CREATE CONSTRAINT TRIGGER workday_reward_pair AFTER INSERT ON trimmy.workday_completions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION trimmy.check_workday_reward();
CREATE CONSTRAINT TRIGGER workday_ledger_pair AFTER INSERT ON trimmy.career_trim_ledger DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION trimmy.check_workday_reward();
CREATE FUNCTION trimmy.workday_read(viewer uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,trimmy,pg_temp AS $$
DECLARE entries jsonb; done_count integer;
BEGIN
 IF viewer IS NULL OR trimmy.practice_current_user() IS DISTINCT FROM viewer OR NOT EXISTS(SELECT 1 FROM trimmy.users WHERE id=viewer AND status='active') THEN RAISE EXCEPTION 'ACCOUNT_REQUIRED'; END IF;
 SELECT count(*) INTO done_count FROM trimmy.workday_completions WHERE user_id=viewer;
 SELECT jsonb_agg((d.payload-'feedback'-'context') || jsonb_build_object(
  'evidence',((d.payload->'evidence')-'requiredIds') || jsonb_build_object('count',jsonb_array_length(d.payload->'evidence'->'requiredIds')),
  'decision',(d.payload->'decision')-'acceptedAnswers',
  'file',((d.payload->'file')-'requiredIds') || jsonb_build_object('count',jsonb_array_length(d.payload->'file'->'requiredIds')),
  'revision',coalesce(a.revision,0),'step',coalesce(a.step,0),'answers',coalesce(a.answers,'{}'), 'draft',coalesce(a.draft,''),
  'completedAt',c.completed_at,'artifact',c.artifact,'feedback',CASE WHEN c.id IS NOT NULL THEN d.payload->>'feedback' ELSE NULL END,
  'contextNote',CASE WHEN d.payload->'context' IS NOT NULL THEN
   (d.payload->'context'->'responses')->>(SELECT p.answers->'1'->>'value' FROM trimmy.workday_attempts p WHERE p.user_id=viewer AND p.assignment_id=(d.payload->'context'->>'fromId')) ELSE NULL END
 ) ORDER BY d.ordinal) INTO entries
 FROM trimmy.workday_definitions d LEFT JOIN trimmy.workday_attempts a ON a.user_id=viewer AND a.assignment_id=d.id LEFT JOIN trimmy.workday_completions c ON c.user_id=viewer AND c.assignment_id=d.id;
 RETURN jsonb_build_object('contentVersion','intern-2026-09-24.1','date',trimmy.career_local_date(viewer,clock_timestamp()),'completedCount',done_count,'assignments',entries);
END; $$;
REVOKE ALL ON FUNCTION trimmy.workday_read(uuid) FROM PUBLIC;
CREATE FUNCTION trimmy.workday_save(viewer uuid, selected_id text, expected_revision integer, selected_step integer, selected_answer jsonb, selected_draft text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,trimmy,pg_temp AS $$
DECLARE d trimmy.workday_definitions%ROWTYPE; a trimmy.workday_attempts%ROWTYPE; required_ids jsonb; answer jsonb; at_time timestamptz; local_day date; rev bigint; completion uuid; artifact_text text;
BEGIN
 IF viewer IS NULL OR trimmy.practice_current_user() IS DISTINCT FROM viewer OR NOT EXISTS(SELECT 1 FROM trimmy.users WHERE id=viewer AND status='active') THEN RAISE EXCEPTION 'ACCOUNT_REQUIRED'; END IF;
 IF expected_revision IS NULL OR expected_revision<0 OR selected_step IS NULL THEN RAISE EXCEPTION 'INVALID_WORK'; END IF;
 IF selected_draft IS NOT NULL AND (char_length(selected_draft)>280 OR selected_draft ~ '[\x00-\x08\x0B\x0C\x0E-\x1F]') THEN RAISE EXCEPTION 'INVALID_WORK'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended('trimmy.career:'||viewer::text,0));
 SELECT * INTO d FROM trimmy.workday_definitions WHERE id=selected_id;
 IF d.id IS NULL THEN RAISE EXCEPTION 'INVALID_WORK'; END IF;
 IF EXISTS(SELECT 1 FROM trimmy.workday_definitions prev WHERE prev.ordinal<d.ordinal AND NOT EXISTS(SELECT 1 FROM trimmy.workday_completions c WHERE c.user_id=viewer AND c.assignment_id=prev.id)) THEN RAISE EXCEPTION 'WORK_LOCKED'; END IF;
 INSERT INTO trimmy.workday_attempts(user_id,assignment_id) VALUES(viewer,selected_id) ON CONFLICT DO NOTHING;
 SELECT * INTO a FROM trimmy.workday_attempts WHERE user_id=viewer AND assignment_id=selected_id FOR UPDATE;
 IF selected_step=-1 THEN
  IF selected_draft IS NULL OR a.step<>2 THEN RAISE EXCEPTION 'WORK_CHANGED'; END IF;
  IF a.draft=selected_draft THEN RETURN trimmy.workday_read(viewer); END IF;
  IF a.revision<>expected_revision THEN RAISE EXCEPTION 'WORK_CHANGED'; END IF;
  UPDATE trimmy.workday_attempts SET draft=selected_draft,revision=revision+1,updated_at=clock_timestamp() WHERE user_id=viewer AND assignment_id=selected_id;
  RETURN trimmy.workday_read(viewer);
 END IF;
 answer:=selected_answer;
 IF jsonb_typeof(answer) IS DISTINCT FROM 'object' OR selected_step NOT BETWEEN 0 AND 2 THEN RAISE EXCEPTION 'INVALID_WORK'; END IF;
 IF selected_step IN(0,2) THEN
  required_ids:=CASE WHEN selected_step=0 THEN d.payload->'evidence'->'requiredIds' ELSE d.payload->'file'->'requiredIds' END;
  IF jsonb_typeof(answer->'ids') IS DISTINCT FROM 'array' OR (SELECT count(*) FROM jsonb_object_keys(answer))<>1 THEN RAISE EXCEPTION 'INVALID_WORK'; END IF;
  IF NOT (answer->'ids' @> required_ids AND required_ids @> (answer->'ids')) OR jsonb_array_length(answer->'ids')<>jsonb_array_length(required_ids) THEN RAISE EXCEPTION 'CHECK_EVIDENCE'; END IF;
  SELECT jsonb_build_object('ids',jsonb_agg(v ORDER BY v)) INTO answer FROM jsonb_array_elements(answer->'ids') v;
 ELSE
  IF jsonb_typeof(answer->'value') IS DISTINCT FROM 'string' OR (SELECT count(*) FROM jsonb_object_keys(answer))<>1 THEN RAISE EXCEPTION 'INVALID_WORK'; END IF;
  IF d.payload->'decision'->>'kind'='number' THEN
   IF answer->>'value' !~ '^-?[0-9]{1,9}(\.[0-9]{1,6})?$' THEN RAISE EXCEPTION 'CHECK_DECISION'; END IF;
   IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements_text(d.payload->'decision'->'acceptedAnswers') v WHERE v::numeric=(answer->>'value')::numeric) THEN RAISE EXCEPTION 'CHECK_DECISION'; END IF;
   answer:=jsonb_build_object('value',trim_scale((answer->>'value')::numeric)::text);
  ELSIF NOT (d.payload->'decision'->'acceptedAnswers' ? (answer->>'value')) THEN RAISE EXCEPTION 'CHECK_DECISION'; END IF;
 END IF;
 IF a.step>selected_step AND a.answers->selected_step::text=answer AND (selected_step<>2 OR selected_draft IS NULL OR selected_draft=a.draft) THEN RETURN trimmy.workday_read(viewer); END IF;
 IF a.revision<>expected_revision OR a.step<>selected_step THEN RAISE EXCEPTION 'WORK_CHANGED'; END IF;
 UPDATE trimmy.workday_attempts SET step=step+1,revision=revision+1,answers=answers||jsonb_build_object(selected_step::text,answer),draft=coalesce(selected_draft,draft),updated_at=clock_timestamp() WHERE user_id=viewer AND assignment_id=selected_id;
 IF selected_step=2 THEN
  SELECT string_agg(p->>'text',E'\n' ORDER BY ord) INTO artifact_text FROM jsonb_array_elements(d.payload->'file'->'parts') WITH ORDINALITY AS parts(p,ord) WHERE required_ids ? (p->>'id');
  IF length(btrim(coalesce(selected_draft,a.draft)))>0 THEN artifact_text:=artifact_text||E'\n\n'||btrim(coalesce(selected_draft,a.draft)); END IF;
  at_time:=clock_timestamp(); local_day:=trimmy.career_local_date(viewer,at_time);
  rev:=trimmy.career_record_activity(viewer,local_day,20,at_time);
  INSERT INTO trimmy.workday_completions(user_id,assignment_id,artifact,completed_at,completed_date) VALUES(viewer,selected_id,artifact_text,at_time,local_day) RETURNING id INTO completion;
  INSERT INTO trimmy.career_trim_ledger(user_id,career_revision,entry_kind,source_id,trims,awarded_on,created_at) VALUES(viewer,rev,'workday',completion,20,local_day,at_time);
  INSERT INTO trimmy.career_activity_events(user_id,activity_kind,source_id,observed_at) VALUES(viewer,'workday',completion,at_time);
 END IF;
 RETURN trimmy.workday_read(viewer);
END; $$;
REVOKE ALL ON FUNCTION trimmy.workday_save(uuid,text,integer,integer,jsonb,text) FROM PUBLIC;
INSERT INTO trimmy.schema_migrations(version) VALUES('0030_intern_workdays');
COMMIT;
